### PR TITLE
add NightFilenameGen to generate engineering visits

### PR DESCRIPTION
**Pull request by alefur**

### CODE REVIEW

**Review by CraigLoomis — COMMENTED** [review]
So I was thinking of manual visit generation as an absolute last-ditch mechanism, which would never ever get used, unless the gen2 actor was not running or not reachable, or the acquisition routines were being run outside of an actor.

In nearly all normal cases, if an actor had not been told a visit it would simply ask the gen2 actor itself, and the gen2 actor would be reachable. That is what we currently do in the MCS actor.

**Comment by alefur** [comment]
Okay, was wrong. I was assuming that iicActor would be the **only** interface between gen2Actor and the other actors.

**Comment by CraigLoomis** [comment]
It is for all non-engineering operations. The issue is to cover two cases: when a ccd/hx/mcs/agcc actor is asked to take an exposure directly (and not via iicActor), and when you are not even using an actor, but just the acquisition routines. In the first case, the actor should ask the gen2 actor for a visit directly; in the second it has to make a filename itself.

**Comment by alefur** [comment]
Got it. 
Well, the second case is already covered then, and for the first one 
```
def _fetchVisitFromGen2(self):
        """Actually get a new visit from Gen2.
        What PFS calls a "visit", Gen2 calls a "frame".
        """
        ret = self.actor.cmdr.call(actor='gen2', cmdStr='getVisit', timeLim=10.0)
        if ret.didFail:
            raise RuntimeError("Failed to get a visit number in 10s!")

        visit = self.actor.models['gen2'].keyVarDict['visit'].valueList[0]
        return visit
```
I'm not sure about adding directly that function to actorcore.Actor, it's seems very subaru specific to me.

**Comment by CraigLoomis** [comment]
Agreed that is a bit Subaru specific, but I don’t know if it is worth adding another product for such things (ics_pfsutils? pfs_icsutils?)? Might be.

**Pull request merged**
